version: "3"

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

services:
  zookeper:
    image: 'bitnami/zookeeper:latest'
    networks:
      - frontend
      - backend
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    networks:
      - backend
    environment:
      - KAFKA_BROKER_ID:1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeper

  redis:
    image: 'redis:latest'
    networks:
      - backend

  game:
    image: jnp-rock-paper-money/game
    networks:
      - backend
    build:
      context: ./game
    depends_on:
      - kafka
      - redis
#    for testing
    ports:
      - 8080:8080

  gateway:
    image: jnp-rock-paper-money/gateway
    networks:
        - backend
        - frontend
    build:
      context: ./gateway
    depends_on:
      - kafka

  matchmaking:
    image: jnp-rock-paper-money/matchmaking
    networks:
        - backend
    build:
      context: ./matchmaking
    depends_on:
      - kafka

  user:
    image: jnp-rock-paper-money/user
    networks:
        - backend
    build:
      context: ./user
    depends_on:
      - kafka
