apiVersion: v1
kind: Service
metadata:
  name: redis-user
  labels:
    app: redis-user
    tier: backend
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis-user
    tier: backend
