apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-matchmaking
  labels:
    app: redis-matchmaking
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-matchmaking
  template:
    metadata:
      labels:
        app: redis-matchmaking
        tier: backend
    spec:
      containers:
        - name: redis-matchmaking
          image: "docker.io/redis:6.0.5"
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 6379
