apiVersion: v1
kind: Service
metadata:
  name: redis-matchmaking
  labels:
    app: redis-matchmaking
    tier: backend
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis-matchmaking
    tier: backend
