apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-deploy
  labels:
    app: game
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
        - name: game
          image: gcr.io/mesmerizing-app-280416/game
          ports:
            - containerPort: 8080
