apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
    tier: backend
spec:
  type: LoadBalancer
  ports:
    - port: 8080
  selector:
    app: gateway
    tier: backend
