apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 8080
  selector:
    app: frontend
    tier: frontend
