apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deploy
  labels:
    app: user
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: gcr.io/mesmerizing-app-280416/user
          ports:
            - containerPort: 8080
